spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          batch_size: 400
          order_inserts: true
          order_updates: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
#    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://114.115.180.42:3306/pt2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true
    #    url: jdbc:mysql://localhost:3306/index_point?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #    password: 123456
    password: root
  main:
    allow-bean-definition-overriding: true
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: bearer
  route:
    authentication:
      path: /auth
      refresh: /refresh
batch-size: 400